'------------------------------------------------------------------------------
' <auto-generated>
'     Ce code a été généré par un outil.
'     Version du runtime :4.0.30319.42000
'
'     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
'     le code est régénéré.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Fonctionnalité Enregistrement automatique My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("localhost")>  _
        Public Property DBServer() As String
            Get
                Return CType(Me("DBServer"),String)
            End Get
            Set
                Me("DBServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property DBName() As String
            Get
                Return CType(Me("DBName"),String)
            End Get
            Set
                Me("DBName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("root")>  _
        Public Property UserName() As String
            Get
                Return CType(Me("UserName"),String)
            End Get
            Set
                Me("UserName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property UserPassword() As String
            Get
                Return CType(Me("UserPassword"),String)
            End Get
            Set
                Me("UserPassword") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MySql.Data.MySqlClient")>  _
        Public Property DBProvider() As String
            Get
                Return CType(Me("DBProvider"),String)
            End Get
            Set
                Me("DBProvider") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplayTableAndFieldDescription() As Boolean
            Get
                Return CType(Me("DisplayTableAndFieldDescription"),Boolean)
            End Get
            Set
                Me("DisplayTableAndFieldDescription") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplayFieldType() As Boolean
            Get
                Return CType(Me("DisplayFieldType"),Boolean)
            End Get
            Set
                Me("DisplayFieldType") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplayFieldDefaultValue() As Boolean
            Get
                Return CType(Me("DisplayFieldDefaultValue"),Boolean)
            End Get
            Set
                Me("DisplayFieldDefaultValue") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisplayLinkName() As Boolean
            Get
                Return CType(Me("DisplayLinkName"),Boolean)
            End Get
            Set
                Me("DisplayLinkName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SortColumns() As Boolean
            Get
                Return CType(Me("SortColumns"),Boolean)
            End Get
            Set
                Me("SortColumns") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SortIndexes() As Boolean
            Get
                Return CType(Me("SortIndexes"),Boolean)
            End Get
            Set
                Me("SortIndexes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SortLinks() As Boolean
            Get
                Return CType(Me("SortLinks"),Boolean)
            End Get
            Set
                Me("SortLinks") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AlertNotNullable() As Boolean
            Get
                Return CType(Me("AlertNotNullable"),Boolean)
            End Get
            Set
                Me("AlertNotNullable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RESTRICT")>  _
        Public Property ForeignKeyDeleteRule() As String
            Get
                Return CType(Me("ForeignKeyDeleteRule"),String)
            End Get
            Set
                Me("ForeignKeyDeleteRule") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RESTRICT")>  _
        Public Property ForeignKeyUpdateRule() As String
            Get
                Return CType(Me("ForeignKeyUpdateRule"),String)
            End Get
            Set
                Me("ForeignKeyUpdateRule") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("InnoDB")>  _
        Public Property MySqlTableEngine() As String
            Get
                Return CType(Me("MySqlTableEngine"),String)
            End Get
            Set
                Me("MySqlTableEngine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("utf8_general_ci")>  _
        Public Property MySqlServerCollation() As String
            Get
                Return CType(Me("MySqlServerCollation"),String)
            End Get
            Set
                Me("MySqlServerCollation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("utf8_general_ci")>  _
        Public Property MySqlDatabaseCollation() As String
            Get
                Return CType(Me("MySqlDatabaseCollation"),String)
            End Get
            Set
                Me("MySqlDatabaseCollation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("utf8_general_ci")>  _
        Public Property MySqlTableCollation() As String
            Get
                Return CType(Me("MySqlTableCollation"),String)
            End Get
            Set
                Me("MySqlTableCollation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("utf8_general_ci")>  _
        Public Property MySqlColumnCollation() As String
            Get
                Return CType(Me("MySqlColumnCollation"),String)
            End Get
            Set
                Me("MySqlColumnCollation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION")>  _
        Public Property MySqlSQLMode() As String
            Get
                Return CType(Me("MySqlSQLMode"),String)
            End Get
            Set
                Me("MySqlSQLMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ON")>  _
        Public Property MySqlInnodbStrictMode() As String
            Get
                Return CType(Me("MySqlInnodbStrictMode"),String)
            End Get
            Set
                Me("MySqlInnodbStrictMode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("99999")>  _
        Public Property MySqlTimeOutMaxSec() As Integer
            Get
                Return CType(Me("MySqlTimeOutMaxSec"),Integer)
            End Get
            Set
                Me("MySqlTimeOutMaxSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property MySqlNetReadTimeoutSec() As Integer
            Get
                Return CType(Me("MySqlNetReadTimeoutSec"),Integer)
            End Get
            Set
                Me("MySqlNetReadTimeoutSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property MySqlNetWriteTimeoutSec() As Integer
            Get
                Return CType(Me("MySqlNetWriteTimeoutSec"),Integer)
            End Get
            Set
                Me("MySqlNetWriteTimeoutSec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MySqlDisplayTableEngine() As Boolean
            Get
                Return CType(Me("MySqlDisplayTableEngine"),Boolean)
            End Get
            Set
                Me("MySqlDisplayTableEngine") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MySqlDisplayCollation() As Boolean
            Get
                Return CType(Me("MySqlDisplayCollation"),Boolean)
            End Get
            Set
                Me("MySqlDisplayCollation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property InstanceName() As String
            Get
                Return CType(Me("InstanceName"),String)
            End Get
            Set
                Me("InstanceName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Port() As String
            Get
                Return CType(Me("Port"),String)
            End Get
            Set
                Me("Port") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SortTables() As Boolean
            Get
                Return CType(Me("SortTables"),Boolean)
            End Get
            Set
                Me("SortTables") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisplayAutonumberAsPrimaryKey() As Boolean
            Get
                Return CType(Me("DisplayAutonumberAsPrimaryKey"),Boolean)
            End Get
            Set
                Me("DisplayAutonumberAsPrimaryKey") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplayMultipleIndexName() As Boolean
            Get
                Return CType(Me("DisplayMultipleIndexName"),Boolean)
            End Get
            Set
                Me("DisplayMultipleIndexName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RenameSQLiteMultipleIndex() As Boolean
            Get
                Return CType(Me("RenameSQLiteMultipleIndex"),Boolean)
            End Get
            Set
                Me("RenameSQLiteMultipleIndex") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplaySQLiteSimpleIndexName() As Boolean
            Get
                Return CType(Me("DisplaySQLiteSimpleIndexName"),Boolean)
            End Get
            Set
                Me("DisplaySQLiteSimpleIndexName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplayMySqlParameters() As Boolean
            Get
                Return CType(Me("DisplayMySqlParameters"),Boolean)
            End Get
            Set
                Me("DisplayMySqlParameters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisplayLinksBelowEachTable() As Boolean
            Get
                Return CType(Me("DisplayLinksBelowEachTable"),Boolean)
            End Get
            Set
                Me("DisplayLinksBelowEachTable") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property UseUpperCaseIdentifiers() As Boolean
            Get
                Return CType(Me("UseUpperCaseIdentifiers"),Boolean)
            End Get
            Set
                Me("UseUpperCaseIdentifiers") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DisplayDateTime() As Boolean
            Get
                Return CType(Me("DisplayDateTime"),Boolean)
            End Get
            Set
                Me("DisplayDateTime") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DisplayStandardSqlType() As Boolean
            Get
                Return CType(Me("DisplayStandardSqlType"),Boolean)
            End Get
            Set
                Me("DisplayStandardSqlType") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.DBReport.My.MySettings
            Get
                Return Global.DBReport.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
